version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies to install for HTML/CSS/Bootstrap"
  build:
    commands:
      - echo "No build step required"
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
